name: test_project
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.1.1
  hive: ^2.2.3
  flutter_facebook_auth: ^5.0.6
  firebase_auth:
  firebase_core: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: circular
      fonts:
        - asset: assets/fonts/Circular.otf
          weight: 400
        - asset: assets/fonts/Circular-Medium.otf
          weight: 500
        - asset: assets/fonts/Circular-Bold.otf
          weight: 600
